USE metabase_db;
DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
    id INT,
    pokedex_number INT,
    name TEXT,
    generation INT,
    status TEXT,
    species TEXT,
    type_number INT,
    type_1 TEXT,
    type_2 TEXT,
    height_m DOUBLE,
    weight_kg DOUBLE,
    abilities_number INT,
    ability_1 TEXT,
    ability_2 TEXT,
    ability_hidden TEXT,
    total_points INT,  -- Changed from GEOMETRY to INT
    hp INT,
    attack INT,
    defense INT,
    sp_attack INT,
    sp_defense INT,
    speed INT,
    catch_rate DOUBLE,
    base_friendship DOUBLE,
    base_experience DOUBLE,
    growth_rate TEXT,
    against_normal DOUBLE,
    against_fire DOUBLE,
    against_water DOUBLE,
    against_electric DOUBLE,
    against_grass DOUBLE,
    against_ice DOUBLE,
    against_fight DOUBLE,
    against_poison DOUBLE,
    against_ground DOUBLE,
    against_flying DOUBLE,
    against_psychic DOUBLE,
    against_bug DOUBLE,
    against_rock DOUBLE,
    against_ghost DOUBLE,
    against_dragon DOUBLE,
    against_dark DOUBLE,
    against_steel DOUBLE,
    against_fairy DOUBLE
);
